version: "3.8"

# docker compose up
services:
  # docker compose up frontend
  frontend:
    build: frontend
    hostname: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # docker compose up backend
  backend:
    build: backend
    hostname: backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb

  # docker compose up mongodb
  mongodb:
    image: mongo:6.0.5
    hostname: mongodb
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: usr
      MONGO_INITDB_ROOT_PASSWORD: pwd