spring:
  mongodb:
    embedded:
      version: 4.4.11
  data:
    mongodb:
      port: 8081
      database: library
  main:
    allow-circular-references: true

mongock:
  #  mongo-db:
  #    write-concern:
  #      journal: false
  runner-type: initializingbean
  change-logs-scan-package:
    - ru.otus.spring.hw08.mongock.changelog

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG